### PR TITLE
fix: use correct Code Of Conduct link in README.md

### LINKED ISSUE #685: Code Of Conduct link not working in README.
### Bug description

Clicking the 'Code of Conduct' link from the `README.md` takes you to a 404 page.

### To Reproduce
1. Open `README.md`
2. Click 'Code of Conduct' link towards the top.

### Expected result

Should see `CODE-OF-CONDUCT.md`

### Actual result

See 404 error.

### PR DESCRIPTION
**Pull request by Glazy**
This PR fixes #685 .

- [ ] I've added a unit test to test for potential regressions of this bug. (N/A)
- [ ] The changelog has been updated, if applicable.
- [x] Commits in this PR are minimal and [have descriptive commit messages](https://chris.beams.io/posts/git-commit/).

### CODE REVIEW

**Review by VirginiaBalseiro — APPROVED** [review]

**Comment by VirginiaBalseiro** [comment]
Thank you @Glazy !!

**Comment by ThisIsMissEm** [comment]
Nice catch! I've raised an internal issue for this as it seems it also affects some other SDK repos.

**Comment by NSeydoux** [comment]
I'm closing this because I reapplied the commit in https://github.com/inrupt/solid-ui-react/pull/689, so that the CI/CD runs (because the code change is pushed by a repo owner).

**Comment by NSeydoux** [comment]
Reapplied in https://github.com/inrupt/solid-ui-react/pull/689

**Pull request closed without merging**
